In [2]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [3]:
arr1+arr2

array([11, 22, 33, 44])

In [5]:
arr1-arr2

array([ 9, 18, 27, 36])

In [15]:
arr1*arr2
arr1*2

array([20, 40, 60, 80])

In [7]:
arr1/arr2

array([10., 10., 10., 10.])

In [8]:
arr1**2

array([ 100,  400,  900, 1600])

In [16]:
arr1>20

array([False, False,  True,  True])

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]

array([4, 5, 6])

In [11]:
a[(a % 2) == 0]

array([2, 4, 6])

In [12]:
a[1]

2

In [13]:
a[:2]

array([1, 2])